name: Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.8.3"
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: eu-west-1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' 
      - run: |
            docker buildx build --platform linux/amd64 --tag sam-builder --progress plain .
            cd $GITHUB_WORKSPACE/terraform && sam build